#!/bin/sh

# Get name for new repository
REPOSITORY_NAME=$1

# Check if repository already exists
if ssh git@raspberry "[ -d /home/git/$REPOSITORY_NAME.git ]"; then
	echo "Error: Repository $REPOSITORY_NAME.git already exists on remote server."
	exit
fi

if [ -d "$REPOSITORY_NAME" ]; then
	echo "Error: Repository $REPOSITORY_NAME already exists on local machine."
	exit
fi

# Create new repository on raspberry
echo "Connect to git@raspberry..."
echo "Create new repository $REPOSITORY_NAME on raspberry..."
ssh git@raspberry "mkdir $REPOSITORY_NAME.git && cd $REPOSITORY_NAME.git && git init --bare"
echo "Repository $REPOSITORY_NAME created succesfully."
echo "Close connection to remote host raspberry."

# Create new repository on local machine
echo "Create new repository $REPOSITORY_NAME on local maschine..."
mkdir $REPOSITORY_NAME
cd $REPOSITORY_NAME

echo "Initialize repository $REPOSITORY_NAME..."
git init
git remote add origin git@raspberry:$REPOSITORY_NAME

# Create README.md file for later publication
echo "Create README.md file..."
echo "# $REPOSITORY_NAME" > README.md
git add README.md
git commit -am "Initial commit"

# Configure branch to follow remote-branch master
git push --set-upstream origin master
echo "Finished creating repository $REPOSITORY_NAME."