#!/bin/bash

# Default server
SERVER_DEFAULT="git@raspberry"

# For boolean values
T="t"
F="f"

# Name of readme file
README="README.md"

# Usage of command
USAGE=$(
cat <<EOF
privrepo
	[-r <repository>]
	[-l <user@server>]
	[-o <directory>]
	[-h]
EOF
)

# Retrieve values of given flags
while getopts "l:o:r:h" OPTION; do
	case $OPTION in
		h) 	echo $USAGE;
			IS_HELP="true"
			exit;;
		l) 	REMOTESERV_ADDR=$OPTARG;
			IS_MODIFIED_REMOTESERV_ADDR=$T;;
		o) 	LDIRECTORY_NAME=$OPTARG;
			IS_MODIFIED_LDIRECTORY_NAME=$T;;
		r) 	REPOSITORY_NAME=$OPTARG;
			IS_MODIFIED_REPOSITORY_NAME=$T;;
		\?)	echo $USAGE;;
	esac
done

# Set default boolean values if not defined
: ${IS_HELP=$F}
: ${IS_MODIFIED_REMOTESERV_ADDR=$F}
: ${IS_MODIFIED_LDIRECTORY_NAME=$F}
: ${IS_MODIFIED_REPOSITORY_NAME=$F}

# Error when no repository name is set
if [ "$IS_MODIFIED_REPOSITORY_NAME" == "$F" ] && [ "$IS_HELP" == "$F" ]; then
	echo "You need to specify a name for your repository!"
	echo $USAGE
	exit
fi

# Error when optional arguments -l and/or -o are set but -r is not
if [[ "$IS_MODIFIED_LDIRECTORY_NAME" == "$T" || "$IS_MODIFIED_REMOTESERV_ADDR" == "$T" ]] && [ "$IS_MODIFIED_REPOSITORY_NAME" == "$F" ]; then
	echo "You need to specify a name for your repository!"
	echo $USAGE
	exit
fi

# Replace default values
if [ "$IS_MODIFIED_REMOTESERV_ADDR" == "$F" ]; then
	: ${REMOTESERV_ADDR=$SERVER_DEFAULT}
fi

if [ "$IS_MODIFIED_LDIRECTORY_NAME" == "$F" ]; then
	: ${LDIRECTORY_NAME=$REPOSITORY_NAME}
fi

# Check if repository already exists
if ssh "$REMOTESERV_ADDR" "[ -d /home/git/$REPOSITORY_NAME.git ]"; then
	echo "Error: Repository $REPOSITORY_NAME.git already exists on remote server."
	exit
fi

if [ -d "$LDIRECTORY_NAME" ]; then
	echo "Error: Repository $LDIRECTORY_NAME already exists on local machine."
	exit
fi

# Create new repository on raspberry
echo "Connect to git@raspberry..."
echo "Create new repository $REPOSITORY_NAME on raspberry..."
ssh "$REMOTESERV_ADDR" "mkdir $REPOSITORY_NAME.git && cd $REPOSITORY_NAME.git && git init --bare"
echo "Repository $REPOSITORY_NAME created succesfully."
echo "Close connection to remote host raspberry."

# Create new repository on local machine
echo "Create new repository $LDIRECTORY_NAME on local maschine..."
mkdir "$LDIRECTORY_NAME"
cd "$LDIRECTORY_NAME"

echo "Initialize repository $LDIRECTORY_NAME..."
git init
git remote add origin "$REMOTESERV_ADDR":"$REPOSITORY_NAME"

# Create README.md file for later publication
echo "Create README.md file..."
echo "# $REPOSITORY_NAME" > "$README"
git add "$README"
git commit -am "Initial commit"

# Configure branch to follow remote-branch master
git push --set-upstream origin master
echo "Finished creating repository $LDIRECTORY_NAME."